#pragma once

// This file is automatically generated at CMakeTime Do not edit this file
// directly. Instead edit CMakeModules/version.h.mk

#define @PROJECT_PREFIX@_VERSION "@PROJECT_VERSION@"
#define @PROJECT_PREFIX@_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define @PROJECT_PREFIX@_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define @PROJECT_PREFIX@_VERSION_PATCH @PROJECT_VERSION_PATCH@
